full-website-pullRequest
IvonneBenitesRodriguez/mathmagicians pull request #12
Opened 2023-10-04 21:34 UTC by IvonneBenitesRodriguez

### About this project:
This part of the project is the creation of a full-website for our mathmagicians app.
- For it : I created a feature branch named 11-full-website.
- Also, a folder named pages was created to store a file named Home.js and CalculatorDisplay.js 
- The file Home.js contains an h2 tag and a p tag to display the content of the Home page.
- For a better styling I added classNames for the h2 and for the p tag.
- Also inside my CalculatorDisplay.js I added the functionality of my calculator using the calculate.js and operate.js file
- I installed the react-router-dom 
- And also imported inside my main component : App.js BrowserRouter,NavLink,Routes and Route from react-router-dom
- Inside the App.js I created a Header, with h1 tag and also the navigation bar, and the paths to direct each page.
- The App.js was also styled. 
- Linters also were passed to check if my codebase was correct.

### What was the most complex part of the project?
For me the most complex part was to identify where to add the right Route to direct each component in the right page.

2023-10-04 22:04 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️ ♻️ ♻️

Hi @IvonneBenitesRodriguez,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✅ You set up Gitflow correctly 👍🏽
✅ The Linter checks passed successfully 👍🏽
✅ The app has 3 pages as required 👍🏽
✅ Calculator functions work fine as expected 👍🏽

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-10-04 22:04 UTC, AmaduKamara commented on src/pages/CalculatorDisplay.js
> +          <CalculatorButton className="ac-button" value="AC" onClick={() => handleButtonClick('AC')} />
- [ ] It would be nice if you could align the text to the left and the calculator to the right jus as it's in the wireframe. Let work on it as required in the project wireframe to match your design as provided 👍🏽

<img width="1719" alt="Screenshot 2023-10-04 at 9 51 06 PM" src="https://github.com/IvonneBenitesRodriguez/mathmagicians/assets/50941074/ee803be0-f221-4f7c-b74d-46cbc11dea1f">

2023-10-04 22:04 UTC, AmaduKamara commented on src/App.js
> +        </nav>
- [ ] Kindly move the nav links a bit more to the right as there is too much space left to the right edge. Kindly have spacing to the right from the links similar to the left of the app title. 👍🏽

<img width="1719" alt="Screenshot 2023-10-04 at 9 51 06 PM" src="https://github.com/IvonneBenitesRodriguez/mathmagicians/assets/50941074/ee803be0-f221-4f7c-b74d-46cbc11dea1f">

2023-10-05 03:53 UTC, IvonneBenitesRodriguez commented on src/pages/CalculatorDisplay.js
> +          <CalculatorButton className="ac-button" value="AC" onClick={() => handleButtonClick('AC')} />
Hello @AmaduKamara 👋🏾
Very nice to meet you, thank you for the advices.
I modified that part according your suggestions, 
Best regards,

2023-10-05 03:53 UTC, IvonneBenitesRodriguez commented on src/App.js
> +        </nav>
Hello @AmaduKamara 👋🏾
Very nice to meet you, thank you for the advices.
I modified that part according your suggestions, 
Best regards,

2023-10-05 04:03 UTC, skyv26 approved these changes
## Hi @IvonneBenitesRodriguez , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 
 
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDQ4ZGFlNWE1ZjcyNTVmMDg5ODM5ZTAzNTQxNDhiOGM2ZWJjZDJiMCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/Prquorv3BhAmFeiNo2/giphy.gif)


## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features as previous code Reviewer request ✅ 

## Optional suggestions

- Please make your home page as a default route for your application, right now a person need to manually click on home page in order to see the content. By default your application show blank page.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-05 04:12 UTC, merged